//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMCEvent.Client.KMCEventService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Role {
            get {
                return this.RoleField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleField, value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Blanket", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Blanket : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int BlanketIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BlanketNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FabricField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionNotesField;
        
        private decimal BasePriceField;

        private System.DateTime EventDateField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VenueField;

        private int CapacityField;

        private int CreatedByUserIDField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrganizerNameField;

        private int SeatsRemainingField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int BlanketID {
            get {
                return this.BlanketIDField;
            }
            set {
                if ((this.BlanketIDField.Equals(value) != true)) {
                    this.BlanketIDField = value;
                    this.RaisePropertyChanged("BlanketID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BlanketName {
            get {
                return this.BlanketNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BlanketNameField, value) != true)) {
                    this.BlanketNameField = value;
                    this.RaisePropertyChanged("BlanketName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Fabric {
            get {
                return this.FabricField;
            }
            set {
                if ((object.ReferenceEquals(this.FabricField, value) != true)) {
                    this.FabricField = value;
                    this.RaisePropertyChanged("Fabric");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string DescriptionNotes {
            get {
                return this.DescriptionNotesField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionNotesField, value) != true)) {
                    this.DescriptionNotesField = value;
                    this.RaisePropertyChanged("DescriptionNotes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal BasePrice {
            get {
                return this.BasePriceField;
            }
            set {
                if ((this.BasePriceField.Equals(value) != true)) {
                    this.BasePriceField = value;
                    this.RaisePropertyChanged("BasePrice");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime EventDate {
            get {
                return this.EventDateField;
            }
            set {
                if ((this.EventDateField.Equals(value) != true)) {
                    this.EventDateField = value;
                    this.RaisePropertyChanged("EventDate");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Venue {
            get {
                return this.VenueField;
            }
            set {
                if ((object.ReferenceEquals(this.VenueField, value) != true)) {
                    this.VenueField = value;
                    this.RaisePropertyChanged("Venue");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int Capacity {
            get {
                return this.CapacityField;
            }
            set {
                if ((this.CapacityField.Equals(value) != true)) {
                    this.CapacityField = value;
                    this.RaisePropertyChanged("Capacity");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int CreatedByUserID {
            get {
                return this.CreatedByUserIDField;
            }
            set {
                if ((this.CreatedByUserIDField.Equals(value) != true)) {
                    this.CreatedByUserIDField = value;
                    this.RaisePropertyChanged("CreatedByUserID");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string OrganizerName {
            get {
                return this.OrganizerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OrganizerNameField, value) != true)) {
                    this.OrganizerNameField = value;
                    this.RaisePropertyChanged("OrganizerName");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int SeatsRemaining {
            get {
                return this.SeatsRemainingField;
            }
            set {
                if ((this.SeatsRemainingField.Equals(value) != true)) {
                    this.SeatsRemainingField = value;
                    this.RaisePropertyChanged("SeatsRemaining");
                }
            }
        }

        // Event-domain aliases used by the KMC client code.
        public int EventID {
            get {
                return this.BlanketID;
            }
            set {
                this.BlanketID = value;
            }
        }

        public string Title {
            get {
                return this.BlanketName;
            }
            set {
                this.BlanketName = value;
            }
        }

        public string EventType {
            get {
                return this.Fabric;
            }
            set {
                this.Fabric = value;
            }
        }

        public string Description {
            get {
                return this.DescriptionNotes;
            }
            set {
                this.DescriptionNotes = value;
            }
        }

        public decimal TicketPrice {
            get {
                return this.BasePrice;
            }
            set {
                this.BasePrice = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Inventory", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Inventory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int InventoryIDField;
        
        private int ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BlanketNameField;
        
        private int OwnerUserIDField;
        
        private int UnitsInStockField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EventTypeField;

        private System.DateTime EventDateField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VenueField;

        private System.DateTime RegisteredOnField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int InventoryID {
            get {
                return this.InventoryIDField;
            }
            set {
                if ((this.InventoryIDField.Equals(value) != true)) {
                    this.InventoryIDField = value;
                    this.RaisePropertyChanged("InventoryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string BlanketName {
            get {
                return this.BlanketNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BlanketNameField, value) != true)) {
                    this.BlanketNameField = value;
                    this.RaisePropertyChanged("BlanketName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int OwnerUserID {
            get {
                return this.OwnerUserIDField;
            }
            set {
                if ((this.OwnerUserIDField.Equals(value) != true)) {
                    this.OwnerUserIDField = value;
                    this.RaisePropertyChanged("OwnerUserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int UnitsInStock {
            get {
                return this.UnitsInStockField;
            }
            set {
                if ((this.UnitsInStockField.Equals(value) != true)) {
                    this.UnitsInStockField = value;
                    this.RaisePropertyChanged("UnitsInStock");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string EventType {
            get {
                return this.EventTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.EventTypeField, value) != true)) {
                    this.EventTypeField = value;
                    this.RaisePropertyChanged("EventType");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime EventDate {
            get {
                return this.EventDateField;
            }
            set {
                if ((this.EventDateField.Equals(value) != true)) {
                    this.EventDateField = value;
                    this.RaisePropertyChanged("EventDate");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Venue {
            get {
                return this.VenueField;
            }
            set {
                if ((object.ReferenceEquals(this.VenueField, value) != true)) {
                    this.VenueField = value;
                    this.RaisePropertyChanged("Venue");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.DateTime RegisteredOn {
            get {
                return this.RegisteredOnField;
            }
            set {
                if ((this.RegisteredOnField.Equals(value) != true)) {
                    this.RegisteredOnField = value;
                    this.RaisePropertyChanged("RegisteredOn");
                }
            }
        }

        // Event-domain aliases used by the KMC client code.
        public int RegistrationID {
            get {
                return this.InventoryID;
            }
            set {
                this.InventoryID = value;
            }
        }

        public int EventID {
            get {
                return this.ProductID;
            }
            set {
                this.ProductID = value;
            }
        }

        public string EventTitle {
            get {
                return this.BlanketName;
            }
            set {
                this.BlanketName = value;
            }
        }

        public int ParticipantUserID {
            get {
                return this.OwnerUserID;
            }
            set {
                this.OwnerUserID = value;
            }
        }

        public int SeatCount {
            get {
                return this.UnitsInStock;
            }
            set {
                this.UnitsInStock = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KMCEventService.ApiSoap")]
    public interface ApiSoap {
        
        // CODEGEN: Generating message contract since element name user from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        KMCEvent.Client.KMCEventService.LoginResponse Login(KMCEvent.Client.KMCEventService.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<KMCEvent.Client.KMCEventService.LoginResponse> LoginAsync(KMCEvent.Client.KMCEventService.LoginRequest request);
        
        // CODEGEN: Generating message contract since element name role from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUsersByRole", ReplyAction="*")]
        KMCEvent.Client.KMCEventService.GetUsersByRoleResponse GetUsersByRole(KMCEvent.Client.KMCEventService.GetUsersByRoleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUsersByRole", ReplyAction="*")]
        System.Threading.Tasks.Task<KMCEvent.Client.KMCEventService.GetUsersByRoleResponse> GetUsersByRoleAsync(KMCEvent.Client.KMCEventService.GetUsersByRoleRequest request);
        
        // CODEGEN: Generating message contract since element name Manufacturer_GetBlanketsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Manufacturer_GetBlankets", ReplyAction="*")]
        KMCEvent.Client.KMCEventService.Manufacturer_GetBlanketsResponse Manufacturer_GetBlankets(KMCEvent.Client.KMCEventService.Manufacturer_GetBlanketsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Manufacturer_GetBlankets", ReplyAction="*")]
        System.Threading.Tasks.Task<KMCEvent.Client.KMCEventService.Manufacturer_GetBlanketsResponse> Manufacturer_GetBlanketsAsync(KMCEvent.Client.KMCEventService.Manufacturer_GetBlanketsRequest request);
        
        // CODEGEN: Generating message contract since element name b from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Manufacturer_AddBlanket", ReplyAction="*")]
        KMCEvent.Client.KMCEventService.Manufacturer_AddBlanketResponse Manufacturer_AddBlanket(KMCEvent.Client.KMCEventService.Manufacturer_AddBlanketRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Manufacturer_AddBlanket", ReplyAction="*")]
        System.Threading.Tasks.Task<KMCEvent.Client.KMCEventService.Manufacturer_AddBlanketResponse> Manufacturer_AddBlanketAsync(KMCEvent.Client.KMCEventService.Manufacturer_AddBlanketRequest request);
        
        // CODEGEN: Generating message contract since element name b from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Manufacturer_UpdateBlanket", ReplyAction="*")]
        KMCEvent.Client.KMCEventService.Manufacturer_UpdateBlanketResponse Manufacturer_UpdateBlanket(KMCEvent.Client.KMCEventService.Manufacturer_UpdateBlanketRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Manufacturer_UpdateBlanket", ReplyAction="*")]
        System.Threading.Tasks.Task<KMCEvent.Client.KMCEventService.Manufacturer_UpdateBlanketResponse> Manufacturer_UpdateBlanketAsync(KMCEvent.Client.KMCEventService.Manufacturer_UpdateBlanketRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Manufacturer_DeleteBlanket", ReplyAction="*")]
        void Manufacturer_DeleteBlanket(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Manufacturer_DeleteBlanket", ReplyAction="*")]
        System.Threading.Tasks.Task Manufacturer_DeleteBlanketAsync(int id);
        
        // CODEGEN: Generating message contract since element name Distributor_GetInventoryResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Distributor_GetInventory", ReplyAction="*")]
        KMCEvent.Client.KMCEventService.Distributor_GetInventoryResponse Distributor_GetInventory(KMCEvent.Client.KMCEventService.Distributor_GetInventoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Distributor_GetInventory", ReplyAction="*")]
        System.Threading.Tasks.Task<KMCEvent.Client.KMCEventService.Distributor_GetInventoryResponse> Distributor_GetInventoryAsync(KMCEvent.Client.KMCEventService.Distributor_GetInventoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Distributor_UpdateStock", ReplyAction="*")]
        void Distributor_UpdateStock(int invId, int qty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Distributor_UpdateStock", ReplyAction="*")]
        System.Threading.Tasks.Task Distributor_UpdateStockAsync(int invId, int qty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Distributor_GiveToSeller", ReplyAction="*")]
        void Distributor_GiveToSeller(int distId, int sellerId, int blanketId, int qty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Distributor_GiveToSeller", ReplyAction="*")]
        System.Threading.Tasks.Task Distributor_GiveToSellerAsync(int distId, int sellerId, int blanketId, int qty);
        
        // CODEGEN: Generating message contract since element name query from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchUserStock", ReplyAction="*")]
        KMCEvent.Client.KMCEventService.SearchUserStockResponse SearchUserStock(KMCEvent.Client.KMCEventService.SearchUserStockRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchUserStock", ReplyAction="*")]
        System.Threading.Tasks.Task<KMCEvent.Client.KMCEventService.SearchUserStockResponse> SearchUserStockAsync(KMCEvent.Client.KMCEventService.SearchUserStockRequest request);
        
        // CODEGEN: Generating message contract since element name query from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Seller_SearchBlankets", ReplyAction="*")]
        KMCEvent.Client.KMCEventService.Seller_SearchBlanketsResponse Seller_SearchBlankets(KMCEvent.Client.KMCEventService.Seller_SearchBlanketsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Seller_SearchBlankets", ReplyAction="*")]
        System.Threading.Tasks.Task<KMCEvent.Client.KMCEventService.Seller_SearchBlanketsResponse> Seller_SearchBlanketsAsync(KMCEvent.Client.KMCEventService.Seller_SearchBlanketsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public KMCEvent.Client.KMCEventService.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(KMCEvent.Client.KMCEventService.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string user, string pass) {
            this.user = user;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public KMCEvent.Client.KMCEventService.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(KMCEvent.Client.KMCEventService.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public KMCEvent.Client.KMCEventService.User LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(KMCEvent.Client.KMCEventService.User LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsersByRoleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsersByRole", Namespace="http://tempuri.org/", Order=0)]
        public KMCEvent.Client.KMCEventService.GetUsersByRoleRequestBody Body;
        
        public GetUsersByRoleRequest() {
        }
        
        public GetUsersByRoleRequest(KMCEvent.Client.KMCEventService.GetUsersByRoleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUsersByRoleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string role;
        
        public GetUsersByRoleRequestBody() {
        }
        
        public GetUsersByRoleRequestBody(string role) {
            this.role = role;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsersByRoleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsersByRoleResponse", Namespace="http://tempuri.org/", Order=0)]
        public KMCEvent.Client.KMCEventService.GetUsersByRoleResponseBody Body;
        
        public GetUsersByRoleResponse() {
        }
        
        public GetUsersByRoleResponse(KMCEvent.Client.KMCEventService.GetUsersByRoleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUsersByRoleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public KMCEvent.Client.KMCEventService.User[] GetUsersByRoleResult;
        
        public GetUsersByRoleResponseBody() {
        }
        
        public GetUsersByRoleResponseBody(KMCEvent.Client.KMCEventService.User[] GetUsersByRoleResult) {
            this.GetUsersByRoleResult = GetUsersByRoleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Manufacturer_GetBlanketsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Manufacturer_GetBlankets", Namespace="http://tempuri.org/", Order=0)]
        public KMCEvent.Client.KMCEventService.Manufacturer_GetBlanketsRequestBody Body;
        
        public Manufacturer_GetBlanketsRequest() {
        }
        
        public Manufacturer_GetBlanketsRequest(KMCEvent.Client.KMCEventService.Manufacturer_GetBlanketsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Manufacturer_GetBlanketsRequestBody {
        
        public Manufacturer_GetBlanketsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Manufacturer_GetBlanketsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Manufacturer_GetBlanketsResponse", Namespace="http://tempuri.org/", Order=0)]
        public KMCEvent.Client.KMCEventService.Manufacturer_GetBlanketsResponseBody Body;
        
        public Manufacturer_GetBlanketsResponse() {
        }
        
        public Manufacturer_GetBlanketsResponse(KMCEvent.Client.KMCEventService.Manufacturer_GetBlanketsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Manufacturer_GetBlanketsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public KMCEvent.Client.KMCEventService.Blanket[] Manufacturer_GetBlanketsResult;
        
        public Manufacturer_GetBlanketsResponseBody() {
        }
        
        public Manufacturer_GetBlanketsResponseBody(KMCEvent.Client.KMCEventService.Blanket[] Manufacturer_GetBlanketsResult) {
            this.Manufacturer_GetBlanketsResult = Manufacturer_GetBlanketsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Manufacturer_AddBlanketRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Manufacturer_AddBlanket", Namespace="http://tempuri.org/", Order=0)]
        public KMCEvent.Client.KMCEventService.Manufacturer_AddBlanketRequestBody Body;
        
        public Manufacturer_AddBlanketRequest() {
        }
        
        public Manufacturer_AddBlanketRequest(KMCEvent.Client.KMCEventService.Manufacturer_AddBlanketRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Manufacturer_AddBlanketRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public KMCEvent.Client.KMCEventService.Blanket b;
        
        public Manufacturer_AddBlanketRequestBody() {
        }
        
        public Manufacturer_AddBlanketRequestBody(KMCEvent.Client.KMCEventService.Blanket b) {
            this.b = b;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Manufacturer_AddBlanketResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Manufacturer_AddBlanketResponse", Namespace="http://tempuri.org/", Order=0)]
        public KMCEvent.Client.KMCEventService.Manufacturer_AddBlanketResponseBody Body;
        
        public Manufacturer_AddBlanketResponse() {
        }
        
        public Manufacturer_AddBlanketResponse(KMCEvent.Client.KMCEventService.Manufacturer_AddBlanketResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Manufacturer_AddBlanketResponseBody {
        
        public Manufacturer_AddBlanketResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Manufacturer_UpdateBlanketRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Manufacturer_UpdateBlanket", Namespace="http://tempuri.org/", Order=0)]
        public KMCEvent.Client.KMCEventService.Manufacturer_UpdateBlanketRequestBody Body;
        
        public Manufacturer_UpdateBlanketRequest() {
        }
        
        public Manufacturer_UpdateBlanketRequest(KMCEvent.Client.KMCEventService.Manufacturer_UpdateBlanketRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Manufacturer_UpdateBlanketRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public KMCEvent.Client.KMCEventService.Blanket b;
        
        public Manufacturer_UpdateBlanketRequestBody() {
        }
        
        public Manufacturer_UpdateBlanketRequestBody(KMCEvent.Client.KMCEventService.Blanket b) {
            this.b = b;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Manufacturer_UpdateBlanketResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Manufacturer_UpdateBlanketResponse", Namespace="http://tempuri.org/", Order=0)]
        public KMCEvent.Client.KMCEventService.Manufacturer_UpdateBlanketResponseBody Body;
        
        public Manufacturer_UpdateBlanketResponse() {
        }
        
        public Manufacturer_UpdateBlanketResponse(KMCEvent.Client.KMCEventService.Manufacturer_UpdateBlanketResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Manufacturer_UpdateBlanketResponseBody {
        
        public Manufacturer_UpdateBlanketResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Distributor_GetInventoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Distributor_GetInventory", Namespace="http://tempuri.org/", Order=0)]
        public KMCEvent.Client.KMCEventService.Distributor_GetInventoryRequestBody Body;
        
        public Distributor_GetInventoryRequest() {
        }
        
        public Distributor_GetInventoryRequest(KMCEvent.Client.KMCEventService.Distributor_GetInventoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Distributor_GetInventoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int distId;
        
        public Distributor_GetInventoryRequestBody() {
        }
        
        public Distributor_GetInventoryRequestBody(int distId) {
            this.distId = distId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Distributor_GetInventoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Distributor_GetInventoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public KMCEvent.Client.KMCEventService.Distributor_GetInventoryResponseBody Body;
        
        public Distributor_GetInventoryResponse() {
        }
        
        public Distributor_GetInventoryResponse(KMCEvent.Client.KMCEventService.Distributor_GetInventoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Distributor_GetInventoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public KMCEvent.Client.KMCEventService.Inventory[] Distributor_GetInventoryResult;
        
        public Distributor_GetInventoryResponseBody() {
        }
        
        public Distributor_GetInventoryResponseBody(KMCEvent.Client.KMCEventService.Inventory[] Distributor_GetInventoryResult) {
            this.Distributor_GetInventoryResult = Distributor_GetInventoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchUserStockRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchUserStock", Namespace="http://tempuri.org/", Order=0)]
        public KMCEvent.Client.KMCEventService.SearchUserStockRequestBody Body;
        
        public SearchUserStockRequest() {
        }
        
        public SearchUserStockRequest(KMCEvent.Client.KMCEventService.SearchUserStockRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchUserStockRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string query;
        
        public SearchUserStockRequestBody() {
        }
        
        public SearchUserStockRequestBody(int userId, string query) {
            this.userId = userId;
            this.query = query;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchUserStockResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchUserStockResponse", Namespace="http://tempuri.org/", Order=0)]
        public KMCEvent.Client.KMCEventService.SearchUserStockResponseBody Body;
        
        public SearchUserStockResponse() {
        }
        
        public SearchUserStockResponse(KMCEvent.Client.KMCEventService.SearchUserStockResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchUserStockResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public KMCEvent.Client.KMCEventService.Inventory[] SearchUserStockResult;
        
        public SearchUserStockResponseBody() {
        }
        
        public SearchUserStockResponseBody(KMCEvent.Client.KMCEventService.Inventory[] SearchUserStockResult) {
            this.SearchUserStockResult = SearchUserStockResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Seller_SearchBlanketsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Seller_SearchBlankets", Namespace="http://tempuri.org/", Order=0)]
        public KMCEvent.Client.KMCEventService.Seller_SearchBlanketsRequestBody Body;
        
        public Seller_SearchBlanketsRequest() {
        }
        
        public Seller_SearchBlanketsRequest(KMCEvent.Client.KMCEventService.Seller_SearchBlanketsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Seller_SearchBlanketsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string query;
        
        public Seller_SearchBlanketsRequestBody() {
        }
        
        public Seller_SearchBlanketsRequestBody(string query) {
            this.query = query;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Seller_SearchBlanketsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Seller_SearchBlanketsResponse", Namespace="http://tempuri.org/", Order=0)]
        public KMCEvent.Client.KMCEventService.Seller_SearchBlanketsResponseBody Body;
        
        public Seller_SearchBlanketsResponse() {
        }
        
        public Seller_SearchBlanketsResponse(KMCEvent.Client.KMCEventService.Seller_SearchBlanketsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Seller_SearchBlanketsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public KMCEvent.Client.KMCEventService.Blanket[] Seller_SearchBlanketsResult;
        
        public Seller_SearchBlanketsResponseBody() {
        }
        
        public Seller_SearchBlanketsResponseBody(KMCEvent.Client.KMCEventService.Blanket[] Seller_SearchBlanketsResult) {
            this.Seller_SearchBlanketsResult = Seller_SearchBlanketsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ApiSoapChannel : KMCEvent.Client.KMCEventService.ApiSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ApiSoapClient : System.ServiceModel.ClientBase<KMCEvent.Client.KMCEventService.ApiSoap>, KMCEvent.Client.KMCEventService.ApiSoap {
        
        public ApiSoapClient() {
        }
        
        public ApiSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ApiSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApiSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApiSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KMCEvent.Client.KMCEventService.LoginResponse KMCEvent.Client.KMCEventService.ApiSoap.Login(KMCEvent.Client.KMCEventService.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public KMCEvent.Client.KMCEventService.User Login(string user, string pass) {
            KMCEvent.Client.KMCEventService.LoginRequest inValue = new KMCEvent.Client.KMCEventService.LoginRequest();
            inValue.Body = new KMCEvent.Client.KMCEventService.LoginRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            KMCEvent.Client.KMCEventService.LoginResponse retVal = ((KMCEvent.Client.KMCEventService.ApiSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KMCEvent.Client.KMCEventService.LoginResponse> KMCEvent.Client.KMCEventService.ApiSoap.LoginAsync(KMCEvent.Client.KMCEventService.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<KMCEvent.Client.KMCEventService.LoginResponse> LoginAsync(string user, string pass) {
            KMCEvent.Client.KMCEventService.LoginRequest inValue = new KMCEvent.Client.KMCEventService.LoginRequest();
            inValue.Body = new KMCEvent.Client.KMCEventService.LoginRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            return ((KMCEvent.Client.KMCEventService.ApiSoap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KMCEvent.Client.KMCEventService.GetUsersByRoleResponse KMCEvent.Client.KMCEventService.ApiSoap.GetUsersByRole(KMCEvent.Client.KMCEventService.GetUsersByRoleRequest request) {
            return base.Channel.GetUsersByRole(request);
        }
        
        public KMCEvent.Client.KMCEventService.User[] GetUsersByRole(string role) {
            KMCEvent.Client.KMCEventService.GetUsersByRoleRequest inValue = new KMCEvent.Client.KMCEventService.GetUsersByRoleRequest();
            inValue.Body = new KMCEvent.Client.KMCEventService.GetUsersByRoleRequestBody();
            inValue.Body.role = role;
            KMCEvent.Client.KMCEventService.GetUsersByRoleResponse retVal = ((KMCEvent.Client.KMCEventService.ApiSoap)(this)).GetUsersByRole(inValue);
            return retVal.Body.GetUsersByRoleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KMCEvent.Client.KMCEventService.GetUsersByRoleResponse> KMCEvent.Client.KMCEventService.ApiSoap.GetUsersByRoleAsync(KMCEvent.Client.KMCEventService.GetUsersByRoleRequest request) {
            return base.Channel.GetUsersByRoleAsync(request);
        }
        
        public System.Threading.Tasks.Task<KMCEvent.Client.KMCEventService.GetUsersByRoleResponse> GetUsersByRoleAsync(string role) {
            KMCEvent.Client.KMCEventService.GetUsersByRoleRequest inValue = new KMCEvent.Client.KMCEventService.GetUsersByRoleRequest();
            inValue.Body = new KMCEvent.Client.KMCEventService.GetUsersByRoleRequestBody();
            inValue.Body.role = role;
            return ((KMCEvent.Client.KMCEventService.ApiSoap)(this)).GetUsersByRoleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KMCEvent.Client.KMCEventService.Manufacturer_GetBlanketsResponse KMCEvent.Client.KMCEventService.ApiSoap.Manufacturer_GetBlankets(KMCEvent.Client.KMCEventService.Manufacturer_GetBlanketsRequest request) {
            return base.Channel.Manufacturer_GetBlankets(request);
        }
        
        public KMCEvent.Client.KMCEventService.Blanket[] Manufacturer_GetBlankets() {
            KMCEvent.Client.KMCEventService.Manufacturer_GetBlanketsRequest inValue = new KMCEvent.Client.KMCEventService.Manufacturer_GetBlanketsRequest();
            inValue.Body = new KMCEvent.Client.KMCEventService.Manufacturer_GetBlanketsRequestBody();
            KMCEvent.Client.KMCEventService.Manufacturer_GetBlanketsResponse retVal = ((KMCEvent.Client.KMCEventService.ApiSoap)(this)).Manufacturer_GetBlankets(inValue);
            return retVal.Body.Manufacturer_GetBlanketsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KMCEvent.Client.KMCEventService.Manufacturer_GetBlanketsResponse> KMCEvent.Client.KMCEventService.ApiSoap.Manufacturer_GetBlanketsAsync(KMCEvent.Client.KMCEventService.Manufacturer_GetBlanketsRequest request) {
            return base.Channel.Manufacturer_GetBlanketsAsync(request);
        }
        
        public System.Threading.Tasks.Task<KMCEvent.Client.KMCEventService.Manufacturer_GetBlanketsResponse> Manufacturer_GetBlanketsAsync() {
            KMCEvent.Client.KMCEventService.Manufacturer_GetBlanketsRequest inValue = new KMCEvent.Client.KMCEventService.Manufacturer_GetBlanketsRequest();
            inValue.Body = new KMCEvent.Client.KMCEventService.Manufacturer_GetBlanketsRequestBody();
            return ((KMCEvent.Client.KMCEventService.ApiSoap)(this)).Manufacturer_GetBlanketsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KMCEvent.Client.KMCEventService.Manufacturer_AddBlanketResponse KMCEvent.Client.KMCEventService.ApiSoap.Manufacturer_AddBlanket(KMCEvent.Client.KMCEventService.Manufacturer_AddBlanketRequest request) {
            return base.Channel.Manufacturer_AddBlanket(request);
        }
        
        public void Manufacturer_AddBlanket(KMCEvent.Client.KMCEventService.Blanket b) {
            KMCEvent.Client.KMCEventService.Manufacturer_AddBlanketRequest inValue = new KMCEvent.Client.KMCEventService.Manufacturer_AddBlanketRequest();
            inValue.Body = new KMCEvent.Client.KMCEventService.Manufacturer_AddBlanketRequestBody();
            inValue.Body.b = b;
            KMCEvent.Client.KMCEventService.Manufacturer_AddBlanketResponse retVal = ((KMCEvent.Client.KMCEventService.ApiSoap)(this)).Manufacturer_AddBlanket(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KMCEvent.Client.KMCEventService.Manufacturer_AddBlanketResponse> KMCEvent.Client.KMCEventService.ApiSoap.Manufacturer_AddBlanketAsync(KMCEvent.Client.KMCEventService.Manufacturer_AddBlanketRequest request) {
            return base.Channel.Manufacturer_AddBlanketAsync(request);
        }
        
        public System.Threading.Tasks.Task<KMCEvent.Client.KMCEventService.Manufacturer_AddBlanketResponse> Manufacturer_AddBlanketAsync(KMCEvent.Client.KMCEventService.Blanket b) {
            KMCEvent.Client.KMCEventService.Manufacturer_AddBlanketRequest inValue = new KMCEvent.Client.KMCEventService.Manufacturer_AddBlanketRequest();
            inValue.Body = new KMCEvent.Client.KMCEventService.Manufacturer_AddBlanketRequestBody();
            inValue.Body.b = b;
            return ((KMCEvent.Client.KMCEventService.ApiSoap)(this)).Manufacturer_AddBlanketAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KMCEvent.Client.KMCEventService.Manufacturer_UpdateBlanketResponse KMCEvent.Client.KMCEventService.ApiSoap.Manufacturer_UpdateBlanket(KMCEvent.Client.KMCEventService.Manufacturer_UpdateBlanketRequest request) {
            return base.Channel.Manufacturer_UpdateBlanket(request);
        }
        
        public void Manufacturer_UpdateBlanket(KMCEvent.Client.KMCEventService.Blanket b) {
            KMCEvent.Client.KMCEventService.Manufacturer_UpdateBlanketRequest inValue = new KMCEvent.Client.KMCEventService.Manufacturer_UpdateBlanketRequest();
            inValue.Body = new KMCEvent.Client.KMCEventService.Manufacturer_UpdateBlanketRequestBody();
            inValue.Body.b = b;
            KMCEvent.Client.KMCEventService.Manufacturer_UpdateBlanketResponse retVal = ((KMCEvent.Client.KMCEventService.ApiSoap)(this)).Manufacturer_UpdateBlanket(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KMCEvent.Client.KMCEventService.Manufacturer_UpdateBlanketResponse> KMCEvent.Client.KMCEventService.ApiSoap.Manufacturer_UpdateBlanketAsync(KMCEvent.Client.KMCEventService.Manufacturer_UpdateBlanketRequest request) {
            return base.Channel.Manufacturer_UpdateBlanketAsync(request);
        }
        
        public System.Threading.Tasks.Task<KMCEvent.Client.KMCEventService.Manufacturer_UpdateBlanketResponse> Manufacturer_UpdateBlanketAsync(KMCEvent.Client.KMCEventService.Blanket b) {
            KMCEvent.Client.KMCEventService.Manufacturer_UpdateBlanketRequest inValue = new KMCEvent.Client.KMCEventService.Manufacturer_UpdateBlanketRequest();
            inValue.Body = new KMCEvent.Client.KMCEventService.Manufacturer_UpdateBlanketRequestBody();
            inValue.Body.b = b;
            return ((KMCEvent.Client.KMCEventService.ApiSoap)(this)).Manufacturer_UpdateBlanketAsync(inValue);
        }
        
        public void Manufacturer_DeleteBlanket(int id) {
            base.Channel.Manufacturer_DeleteBlanket(id);
        }
        
        public System.Threading.Tasks.Task Manufacturer_DeleteBlanketAsync(int id) {
            return base.Channel.Manufacturer_DeleteBlanketAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KMCEvent.Client.KMCEventService.Distributor_GetInventoryResponse KMCEvent.Client.KMCEventService.ApiSoap.Distributor_GetInventory(KMCEvent.Client.KMCEventService.Distributor_GetInventoryRequest request) {
            return base.Channel.Distributor_GetInventory(request);
        }
        
        public KMCEvent.Client.KMCEventService.Inventory[] Distributor_GetInventory(int distId) {
            KMCEvent.Client.KMCEventService.Distributor_GetInventoryRequest inValue = new KMCEvent.Client.KMCEventService.Distributor_GetInventoryRequest();
            inValue.Body = new KMCEvent.Client.KMCEventService.Distributor_GetInventoryRequestBody();
            inValue.Body.distId = distId;
            KMCEvent.Client.KMCEventService.Distributor_GetInventoryResponse retVal = ((KMCEvent.Client.KMCEventService.ApiSoap)(this)).Distributor_GetInventory(inValue);
            return retVal.Body.Distributor_GetInventoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KMCEvent.Client.KMCEventService.Distributor_GetInventoryResponse> KMCEvent.Client.KMCEventService.ApiSoap.Distributor_GetInventoryAsync(KMCEvent.Client.KMCEventService.Distributor_GetInventoryRequest request) {
            return base.Channel.Distributor_GetInventoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<KMCEvent.Client.KMCEventService.Distributor_GetInventoryResponse> Distributor_GetInventoryAsync(int distId) {
            KMCEvent.Client.KMCEventService.Distributor_GetInventoryRequest inValue = new KMCEvent.Client.KMCEventService.Distributor_GetInventoryRequest();
            inValue.Body = new KMCEvent.Client.KMCEventService.Distributor_GetInventoryRequestBody();
            inValue.Body.distId = distId;
            return ((KMCEvent.Client.KMCEventService.ApiSoap)(this)).Distributor_GetInventoryAsync(inValue);
        }
        
        public void Distributor_UpdateStock(int invId, int qty) {
            base.Channel.Distributor_UpdateStock(invId, qty);
        }
        
        public System.Threading.Tasks.Task Distributor_UpdateStockAsync(int invId, int qty) {
            return base.Channel.Distributor_UpdateStockAsync(invId, qty);
        }
        
        public void Distributor_GiveToSeller(int distId, int sellerId, int blanketId, int qty) {
            base.Channel.Distributor_GiveToSeller(distId, sellerId, blanketId, qty);
        }
        
        public System.Threading.Tasks.Task Distributor_GiveToSellerAsync(int distId, int sellerId, int blanketId, int qty) {
            return base.Channel.Distributor_GiveToSellerAsync(distId, sellerId, blanketId, qty);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KMCEvent.Client.KMCEventService.SearchUserStockResponse KMCEvent.Client.KMCEventService.ApiSoap.SearchUserStock(KMCEvent.Client.KMCEventService.SearchUserStockRequest request) {
            return base.Channel.SearchUserStock(request);
        }
        
        public KMCEvent.Client.KMCEventService.Inventory[] SearchUserStock(int userId, string query) {
            KMCEvent.Client.KMCEventService.SearchUserStockRequest inValue = new KMCEvent.Client.KMCEventService.SearchUserStockRequest();
            inValue.Body = new KMCEvent.Client.KMCEventService.SearchUserStockRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.query = query;
            KMCEvent.Client.KMCEventService.SearchUserStockResponse retVal = ((KMCEvent.Client.KMCEventService.ApiSoap)(this)).SearchUserStock(inValue);
            return retVal.Body.SearchUserStockResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KMCEvent.Client.KMCEventService.SearchUserStockResponse> KMCEvent.Client.KMCEventService.ApiSoap.SearchUserStockAsync(KMCEvent.Client.KMCEventService.SearchUserStockRequest request) {
            return base.Channel.SearchUserStockAsync(request);
        }
        
        public System.Threading.Tasks.Task<KMCEvent.Client.KMCEventService.SearchUserStockResponse> SearchUserStockAsync(int userId, string query) {
            KMCEvent.Client.KMCEventService.SearchUserStockRequest inValue = new KMCEvent.Client.KMCEventService.SearchUserStockRequest();
            inValue.Body = new KMCEvent.Client.KMCEventService.SearchUserStockRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.query = query;
            return ((KMCEvent.Client.KMCEventService.ApiSoap)(this)).SearchUserStockAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KMCEvent.Client.KMCEventService.Seller_SearchBlanketsResponse KMCEvent.Client.KMCEventService.ApiSoap.Seller_SearchBlankets(KMCEvent.Client.KMCEventService.Seller_SearchBlanketsRequest request) {
            return base.Channel.Seller_SearchBlankets(request);
        }
        
        public KMCEvent.Client.KMCEventService.Blanket[] Seller_SearchBlankets(string query) {
            KMCEvent.Client.KMCEventService.Seller_SearchBlanketsRequest inValue = new KMCEvent.Client.KMCEventService.Seller_SearchBlanketsRequest();
            inValue.Body = new KMCEvent.Client.KMCEventService.Seller_SearchBlanketsRequestBody();
            inValue.Body.query = query;
            KMCEvent.Client.KMCEventService.Seller_SearchBlanketsResponse retVal = ((KMCEvent.Client.KMCEventService.ApiSoap)(this)).Seller_SearchBlankets(inValue);
            return retVal.Body.Seller_SearchBlanketsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KMCEvent.Client.KMCEventService.Seller_SearchBlanketsResponse> KMCEvent.Client.KMCEventService.ApiSoap.Seller_SearchBlanketsAsync(KMCEvent.Client.KMCEventService.Seller_SearchBlanketsRequest request) {
            return base.Channel.Seller_SearchBlanketsAsync(request);
        }
        
        public System.Threading.Tasks.Task<KMCEvent.Client.KMCEventService.Seller_SearchBlanketsResponse> Seller_SearchBlanketsAsync(string query) {
            KMCEvent.Client.KMCEventService.Seller_SearchBlanketsRequest inValue = new KMCEvent.Client.KMCEventService.Seller_SearchBlanketsRequest();
            inValue.Body = new KMCEvent.Client.KMCEventService.Seller_SearchBlanketsRequestBody();
            inValue.Body.query = query;
            return ((KMCEvent.Client.KMCEventService.ApiSoap)(this)).Seller_SearchBlanketsAsync(inValue);
        }

        // Scenario-friendly wrappers that avoid legacy domain names in client code.
        public KMCEvent.Client.KMCEventService.Blanket[] Organizer_GetMyEvents() {
            return this.Manufacturer_GetBlankets();
        }

        public void Organizer_CreateEvent(KMCEvent.Client.KMCEventService.Blanket eventRecord) {
            this.Manufacturer_AddBlanket(eventRecord);
        }

        public void Organizer_UpdateEvent(KMCEvent.Client.KMCEventService.Blanket eventRecord) {
            this.Manufacturer_UpdateBlanket(eventRecord);
        }

        public void Organizer_ArchiveEvent(int eventId) {
            this.Manufacturer_DeleteBlanket(eventId);
        }

        public KMCEvent.Client.KMCEventService.Inventory[] Participant_GetMyRegistrations(int participantId) {
            return this.Distributor_GetInventory(participantId);
        }

        public void Participant_Register(int participantId, int eventId, int seatCount) {
            this.Distributor_GiveToSeller(participantId, 0, eventId, seatCount);
        }

        public KMCEvent.Client.KMCEventService.Inventory[] Participant_SearchEvents(int participantId, string query) {
            return this.SearchUserStock(participantId, query);
        }

        public KMCEvent.Client.KMCEventService.Blanket[] Public_SearchEvents(string query) {
            return this.Seller_SearchBlankets(query);
        }
    }
}

